#!/bin/sh

LIC=`tempfile`
cat > $LIC << EOL
/* Copyright 2008 Cedric Cellier.
 *
 * This file is part of Scambio.
 *
 * Scambio is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * Scambio is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for
 * more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Scambio.  If not, see <http://www.gnu.org/licenses/>.
 */
EOL

# Make this a sed command (with sed)

sed -i -e 's/\//\\\//g' -e 's/\*/\\\*/g' -e 's/^/1i\ /' $LIC

find . -name '*.c' -o -name '*.h' | xargs sed -ie "$(cat $LIC)"

rm -f $LIC
