#!/bin/sh
set -e

configure() {
	echo "Refreshing GTK icon cache"
	gtk-update-icon-cache -f /usr/share/icons/hicolor/ 2>/dev/null || true
	maemo-select-menu-location vadrouille.desktop 2>/dev/null || true
}

case $1 in
	("configure")         configure $2 ;;
	("abort-upgrade")     true ;;
	("abort-remove")      true ;;
	("abort-deconfigure") true ;;
	("*") exit 1
esac

